# +-------------------------------------------------------+
# |                                                       |
# |               ██████╗ ███████╗██╗   ██╗               |
# |               ██╔══██╗██╔════╝██║   ██║               |
# |               ██████╔╝█████╗  ██║   ██║               |
# |               ██╔══██╗██╔══╝  ╚██╗ ██╔╝               |
# |               ██████╔╝██║      ╚████╔╝                |
# |               ╚═════╝ ╚═╝       ╚═══╝                 |
# |                                                       |
# |     Thank you for downloading Better food values!     |
# |         Please use values.yml to edit values.         |
# |         You can edit all the messages bellow.         |
# |  For help you can reach me on discord: Boris NL#1500  |
# |                                                       |
# +-------------------------------------------------------+