# Thank you for downloading Better Food Values!
# This file is not used, use values.yml to edit values.
# In the future you will be able to edit all the chat messages here.
# You will be notified about a future update in your console and to all staff members.